services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # root password
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # optional initial DB
      MYSQL_USER: ${MYSQL_USER}                    # non-root user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # non-root password
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}                      # use non-root user
      PMA_PASSWORD: ${MYSQL_PASSWORD}              # password for non-root user
    ports:
      - "8080:80"

  backend:
    build: ./backend
    container_name: fastapi_backend
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}                    # use non-root user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

volumes:
  db_data: